/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Business.Business;
import Business.Profiles.EmployerProfile;
import Business.Profiles.ProfessorProfile;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import UserInterface.WorkAreas.AdminRole.AdminDashboardJPanel;
import UserInterface.WorkAreas.EmployerRole.EmployerWorkAreaJPanel;
import UserInterface.WorkAreas.ProfessorRole.ProfessorWorkAreaJPanel;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class LoginJPanel extends javax.swing.JPanel {
    Business business;
    JPanel CardSequencePanel;


    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel(Business bz, JPanel jp) {
        this.business = bz;
        CardSequencePanel = jp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblSignUp = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        txtUsername.setText("professor");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jPasswordField1.setText("professor");

        lblSignUp.setText("To create an account");

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSignUp)
                        .addGap(18, 18, 18)
                        .addComponent(btnSignUp)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignUp)
                    .addComponent(btnSignUp))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:

        // Retrieve username and password from the input fields
        String username = txtUsername.getText();
        char[] passwordChars = jPasswordField1.getPassword();
        String password = new String(passwordChars);

        // Authenticate the user using the UserAccountDirectory
        UserAccountDirectory uad = business.getUserAccountDirectory();
        UserAccount useraccount = uad.authenticate(username, password);

        if (useraccount != null) {
            // Authentication successful
            String role = useraccount.getRole();
            Profile profile = useraccount.getAssociatedPersonProfile();

            if (role.equalsIgnoreCase("Student")) {
                // Handle the case for students
                StudentProfile studentProfile = (StudentProfile) profile;
                StudentWorkAreaJPanel studentWorkAreaJPanel = new StudentWorkAreaJPanel(business, studentProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("student", studentWorkAreaJPanel);
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            } else if (role.equalsIgnoreCase("Professor")) {
                ProfessorProfile professorProfile = (ProfessorProfile) profile;
                ProfessorWorkAreaJPanel professorWorkAreaJPanel = new ProfessorWorkAreaJPanel(business, professorProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("professor", professorWorkAreaJPanel);
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
                // Handle the case for professors
                // Add your code to navigate to the professor panel
            } else if (role.equalsIgnoreCase("Employer")){
                EmployerProfile employerProfile = (EmployerProfile) profile;
                EmployerWorkAreaJPanel employerWorkAreaJPanel = new EmployerWorkAreaJPanel(business, employerProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("employer", employerWorkAreaJPanel);
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
                // Handle other roles or scenarios
            } else if(role.equals("admin")){
                AdminDashboardJPanel panel = new AdminDashboardJPanel(business, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("AdminDashboardJPanel", panel);
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            }
        } else {
            // Authentication failed, handle it as needed (e.g., show an error message)
            JOptionPane.showMessageDialog(this, "Invalid Credentials!!!");
        }

    }                                        

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        SignUpJPanel panel = new SignUpJPanel(business, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("SignUpJPanel", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration                   
}
