/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.Transcripts;

import Business.Business;
import Business.CourseWork.Course;
import Business.Profiles.StudentProfile;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author abhisheksagar
 */
public class GradAuditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GradAuditJPanel
     */
    Business business;
    JPanel CardSequencePanel;
    StudentProfile spp;
    ArrayList<Course> courses;
    public GradAuditJPanel(Business business, JPanel CardSequencePanel, StudentProfile spp) {
        initComponents();
        this.business=business;
        this.CardSequencePanel=CardSequencePanel;
        this.spp=spp;
        
        courses=spp.getCourseList();
        
        if(courses.size()==8){
            for(int i=0;i<8;i++){
                if(courses.get(i).getCourseprogress().equalsIgnoreCase("Completed")){
                    jLabel2.setText("This is to certify that "+spp.getPerson().getFirst_name()+spp.getPerson().getLast_name() +" has Graduated. ");
                }
                else{
                    jLabel2.setText("Complete the courses to get Graduated.");
                    jLabel1.setVisible(false);
                    break;
                }
            }
        }
        else{
                    jLabel2.setText("You have registered for only " +courses.size()+",minimum requirement to graduate is completing 8 courses.");
                    jLabel1.setVisible(false);
                }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Graduation Certificate");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel2.setText("This is to certify that xxxx has Graduated. ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addContainerGap(730, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
