/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.ProfessorRole.CourseWork;

import ui.*;
import Business.Business;
import Business.CourseWork.Course;
import Business.CourseWork.TechStack;
import Business.Person.Person;
import Business.Profiles.ProfessorProfile;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import UserInterface.WorkAreas.ProfessorRole.ProfessorWorkAreaJPanel;
import java.awt.Component;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;


/**
 *
 * @author tirdesh
 */
public class AddCourseJPanel extends javax.swing.JPanel {
    Business business;
    JPanel CardSequencePanel;
    ProfessorProfile professor;


    /**
     * Creates new form AddCourseJPanel
     */
    public AddCourseJPanel(Business bz, ProfessorProfile p, JPanel jp) {
        this.business = bz;
        CardSequencePanel = jp;
        professor = p;
        initComponents();
        modifyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        jRadioButtonStudent = new javax.swing.JRadioButton();
        jRadioButtonProfessor = new javax.swing.JRadioButton();
        btnAddCourse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLastName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPreRequisites = new javax.swing.JComboBox<>();
        jRadioButtonProfessor1 = new javax.swing.JRadioButton();
        lblRole1 = new javax.swing.JLabel();
        jRadioButtonStudent1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProgrammingLanguages = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListFrameworks = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTools = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListClassDays = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        lblLastName.setText("Description:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblFirstName.setText("Name:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblRole.setText("Teaching Type:");

        buttonGroup1.add(jRadioButtonStudent);
        jRadioButtonStudent.setText("Live");
        jRadioButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStudentActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonProfessor);
        jRadioButtonProfessor.setText("Recorded");

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Course");

        lblLastName1.setText("No. Of Hours:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("PreRequisites:");

        jComboBoxPreRequisites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPreRequisites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPreRequisitesActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonProfessor1);
        jRadioButtonProfessor1.setText("On Demand");
        jRadioButtonProfessor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProfessor1ActionPerformed(evt);
            }
        });

        lblRole1.setText("Offering Type:");

        buttonGroup2.add(jRadioButtonStudent1);
        jRadioButtonStudent1.setText("Academic Calendar");
        jRadioButtonStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStudent1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3:");

        jLabel4.setText("jLabel4:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel5.setText("Programming Langauages:");

        jListProgrammingLanguages.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListProgrammingLanguages);

        jListFrameworks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListFrameworks);

        jLabel6.setText("Frameworks:");

        jListTools.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListTools);

        jLabel7.setText("Tools:");

        jListClassDays.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListClassDays);

        jLabel8.setText("Class Days:");

        jLabel9.setText("Class Time:");

        jTextField3.setText("23:23");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLastName1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRole1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRole, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonStudent1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonProfessor1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonProfessor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(jTextField3))
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxPreRequisites, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(btnAddCourse)))
                        .addGap(73, 73, 73)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lblEmail)
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogOut)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblLastName)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblFirstName)
                                            .addGap(30, 30, 30))))
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxPreRequisites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRole)
                        .addComponent(jRadioButtonStudent))
                    .addComponent(jRadioButtonProfessor))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonStudent1)
                            .addComponent(lblRole1))
                        .addComponent(jRadioButtonProfessor1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddCourse)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jRadioButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonStudentActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
    // Get the values entered by the user
    String courseName = txtFirstName.getText();
    String description = jTextArea1.getText();
    int courseHours = Integer.parseInt(txtEmail.getText());

    String sessionType = "";
    if (jRadioButtonStudent.isSelected()) {
        sessionType = "Live";
    } else if (jRadioButtonProfessor.isSelected()) {
        sessionType = "Recorded";
    }

    // Create a new Course object
    Course newCourse = business.getCourseCatalog().newCourse(courseName, description, new ArrayList<>(), courseHours);
    
    // Set the session type for the course
    newCourse.setSessionType(sessionType);
    LocalTime classTime = LocalTime.parse(jTextField3.getText());
            // Fetch class days from jListProgrammingLanguages1
        List<String> selectedClassDays = jListClassDays.getSelectedValuesList();
        List<DayOfWeek> classDays = new ArrayList<>();

        // Convert the selected day strings to DayOfWeek enum values
        for (String selectedDay : selectedClassDays) {
            switch (selectedDay) {
                case "Monday":
                    classDays.add(DayOfWeek.MONDAY);
                    break;
                case "Tuesday":
                    classDays.add(DayOfWeek.TUESDAY);
                    break;
                case "Wednesday":
                    classDays.add(DayOfWeek.WEDNESDAY);
                    break;
                case "Thursday":
                    classDays.add(DayOfWeek.THURSDAY);
                    break;
                case "Friday":
                    classDays.add(DayOfWeek.FRIDAY);
                    break;
                case "Saturday":
                    classDays.add(DayOfWeek.SATURDAY);
                    break;
                case "Sunday":
                    classDays.add(DayOfWeek.SUNDAY);
                    break;
                // Add cases for other days as needed
            }
        }

    
    // Check if it's an academic calendar-based course
    if (jRadioButtonStudent1.isSelected()) {
        String term = jTextField1.getText();
        int termYear = Integer.parseInt(jTextField2.getText());
        // Set course duration for academic calendar-based courses
        newCourse.setCourseDuration(term, termYear, business.getAcademicCalendar());
        newCourse.createLiveClassSchedule(term, termYear, business.getAcademicCalendar(), classTime, classDays);


    } else if (jRadioButtonProfessor1.isSelected()) {
        // Parse the start and end date for on-demand courses
        LocalDate startDate = LocalDate.parse(jTextField1.getText());
        LocalDate endDate = LocalDate.parse(jTextField2.getText());
        // Set course duration for on-demand courses
        newCourse.setCourseDuration(startDate, endDate);
        newCourse.createOnDemandClassSchedule(startDate, endDate, classTime, classDays);
    }
    

    
    // Collect selected programming languages from the JList
    List<String> selectedLanguages = jListProgrammingLanguages.getSelectedValuesList();
    
    // Collect selected frameworks from the JList
    List<String> selectedFrameworks = jListFrameworks.getSelectedValuesList();
    
    // Collect selected tools from the JList
    List<String> selectedTools = jListTools.getSelectedValuesList();
    
    // Create a TechStack object and set the selected lists
    TechStack techStack = new TechStack(selectedLanguages, selectedFrameworks, selectedTools);
    
    // Set the TechStack for the course
    newCourse.setTechStack(techStack);

    // Add the new course to the course catalog
    professor.addCourseToProfile(newCourse);
    
    // Notify the user that the course has been added
    JOptionPane.showMessageDialog(this, "Course has been added successfully!");

    // Clear the input fields
    txtFirstName.setText("");
    jTextArea1.setText("");
    txtEmail.setText("");
    buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    jListProgrammingLanguages.clearSelection();
    jListFrameworks.clearSelection();
    jListTools.clearSelection();
    modifyComponents();
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void jRadioButtonStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStudent1ActionPerformed
        // TODO add your handling code here:
            jLabel3.setText("Term:");
            jLabel4.setText("Year:");
            jLabel3.setVisible(true);
            jTextField1.setVisible(true);
            jLabel4.setVisible(true);
            jTextField2.setVisible(true);
            jTextField1.setText("Fall");
            jTextField2.setText("2023");
            
    }//GEN-LAST:event_jRadioButtonStudent1ActionPerformed

    private void jRadioButtonProfessor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProfessor1ActionPerformed
        // TODO add your handling code here:
            jLabel3.setText("Start Date:");
            jLabel4.setText("End Date:");
            jLabel3.setVisible(true);
            jTextField1.setVisible(true);
            jLabel4.setVisible(true);
            jTextField2.setVisible(true);
            jTextField1.setText("2023-12-31");
            jTextField2.setText("2024-03-31");
    }//GEN-LAST:event_jRadioButtonProfessor1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ProfessorWorkAreaJPanel professorWorkAreaJPanel = new ProfessorWorkAreaJPanel(business, professor, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("professor", professorWorkAreaJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        LoginJPanel panel = new LoginJPanel(business, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("LoginJPanel", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void jComboBoxPreRequisitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPreRequisitesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPreRequisitesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBoxPreRequisites;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListClassDays;
    private javax.swing.JList<String> jListFrameworks;
    private javax.swing.JList<String> jListProgrammingLanguages;
    private javax.swing.JList<String> jListTools;
    private javax.swing.JRadioButton jRadioButtonProfessor;
    private javax.swing.JRadioButton jRadioButtonProfessor1;
    private javax.swing.JRadioButton jRadioButtonStudent;
    private javax.swing.JRadioButton jRadioButtonStudent1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    // End of variables declaration//GEN-END:variables

    private void modifyComponents() {
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        populateCourseComboBox();
        populateTechStack();
        
    }
    public void populateCourseComboBox() {
    // Clear the existing items in the JComboBox
    jComboBoxPreRequisites.removeAllItems();
    jComboBoxPreRequisites.addItem("None");

    // Get the list of courses from the CourseCatalog
    ArrayList<Course> courses = business.getCourseCatalog().getCourseList();

    // Populate the JComboBox with course names
    for (Course course : courses) {
        jComboBoxPreRequisites.addItem(course.getCourseName());
        }
    }
    
    public void populateTechStack() {
    // Create a list of programming languages
    List<String> programmingLanguages = Arrays.asList("Java", "Python", "C++", "JavaScript", "Ruby", "Swift");

    // Create a DefaultListModel to store the programming languages
    DefaultListModel<String> listModelLanguages = new DefaultListModel<>();

    // Add each programming language to the list model
    for (String language : programmingLanguages) {
        listModelLanguages.addElement(language);
    }

    // Set the list model to the JList for programming languages
    jListProgrammingLanguages.setModel(listModelLanguages);

    // Create a list of frameworks
    List<String> frameworks = Arrays.asList("Spring", "Hibernate", "React", "Angular", "Node.js", "Django");

    // Create a DefaultListModel to store the frameworks
    DefaultListModel<String> listModelFrameworks = new DefaultListModel<>();

    // Add each framework to the list model
    for (String framework : frameworks) {
        listModelFrameworks.addElement(framework);
    }

    // Set the list model to the JList for frameworks
    jListFrameworks.setModel(listModelFrameworks);

    // Create a list of tools
    List<String> tools = Arrays.asList("Eclipse", "IntelliJ", "Git", "Visual Studio Code", "PyCharm", "Sublime Text");

    // Create a DefaultListModel to store the tools
    DefaultListModel<String> listModelTools = new DefaultListModel<>();

    // Add each tool to the list model
    for (String tool : tools) {
        listModelTools.addElement(tool);
    }

    // Set the list model to the JList for tools
    jListTools.setModel(listModelTools);
}


    
}
