/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.CourseRegistration;

import Business.Business;
import Business.CourseWork.Course;
import Business.CourseWork.CourseCatalog;
import Business.Employment.Job;
import Business.Profiles.EmployerProfile;
import Business.Profiles.StudentProfile;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import javax.swing.table.TableRowSorter;
import ui.LoginJPanel;

/**
 *
 * @author abhisheksagar
 */
public class NewRegistrationJPanel extends javax.swing.JPanel {
Business business;
//    UserAccount actualuser;
    JPanel CardSequencePanel;
    StudentProfile spp;
    CourseCatalog cc;
    ArrayList<Course> rc;
    /**
     * 
     * Creates new form NewRegistrationJPanel
     */
    public NewRegistrationJPanel(Business business, JPanel CardSequencePanel, StudentProfile spp) {
        initComponents();
        this.CardSequencePanel=CardSequencePanel;
        this.spp=spp;
        this.business=business;
        this.cc=business.getCourseCatalog();
//        populatetable();
        
        modifycomponents();
        ArrayList<String> values = new ArrayList<>();
        for (EmployerProfile employer: business.getEmployerDirectory().getEmployerlist()){
            values.add(employer.getCompanyName());
        }
        populateComboBox(jComboBox1, values);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblregister = new javax.swing.JTable();
        btnLogOut = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        tblregister.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Course Discription", "Term Based", "Duration", "Session Type", "Professor Rating", ""
            }
        ));
        tblregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblregisterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblregister);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(290, 290, 290)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGap(777, 777, 777))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblregisterMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            int row=tblregister.getSelectedRow();
            int col=tblregister.getSelectedColumn();
            System.out.println("function");
            if(col==6){
                System.out.println("7 func");
                DefaultTableModel model = (DefaultTableModel) tblregister.getModel();
                System.out.println(model.getValueAt(row, 1).toString());
                Course c= cc.findCourse(model.getValueAt(row, 0).toString());

                spp.getCourseList().add(c);
                JOptionPane.showMessageDialog(this, "Course Added.");
                rc.remove(c);
                populatetable(rc);

            }
            //            if(col==7){
                //                viewfunction(row);
                //            }
        }
    }//GEN-LAST:event_tblregisterMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        LoginJPanel panel = new LoginJPanel(business, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("LoginJPanel", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //        if(actualuser.getRole().equals("Student")){
            StudentWorkAreaJPanel studentWorkAreaJPanel = new StudentWorkAreaJPanel(business, spp, CardSequencePanel);
            CardSequencePanel.removeAll();
            CardSequencePanel.add("spp", studentWorkAreaJPanel);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            //    }
        //        else{
            //            ProfessorWorkAreaJPanel professorWorkAreaJPanel = new ProfessorWorkAreaJPanel(business, pp, CardSequencePanel);
            //            CardSequencePanel.removeAll();
            //            CardSequencePanel.add("pp", professorWorkAreaJPanel);
            //            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            //        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        TableRowSorter<TableModel> rowSorter= new TableRowSorter<>(tblregister.getModel());
        tblregister.setRowSorter(rowSorter);
        String text = txtsearch.getText();
        if (text.length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter(text));
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedEmployerName = (String) jComboBox1.getSelectedItem();
            //System.out.println("tirdeshggg"+selectedEmployerName);
        if (selectedEmployerName != null && !"Select to Filter".equals(selectedEmployerName)) {
            jComboBox2.setVisible(true);
            ArrayList<String> values = new ArrayList<>();
            EmployerProfile ep = business.getEmployerDirectory().findEmployer(selectedEmployerName);
            if(ep!=null){
                for(Job j:ep.getJobOpenings()){
                    values.add(j.getTitle());
                }
                populateComboBox(jComboBox2, values);
            }
        }
        else{
            jComboBox2.setVisible(false);
            tblregister.setVisible(false);
            jScrollPane1.setVisible(false);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String selectedJobName = (String) jComboBox2.getSelectedItem();

        if (selectedJobName != null && !"Select to Filter".equals(selectedJobName)) {
            tblregister.setVisible(true);
                tblregister.setVisible(true);
    jScrollPane1.setVisible(true);
            Job j = business.getJobCatalog().findJob(selectedJobName);
            ArrayList<Course> relevantCourses = j.getRelevantCourses();
            populatetable(relevantCourses);
            this.rc=relevantCourses;
        }
        else{    
            tblregister.setVisible(false);
    jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblregister;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    private void populatetable(ArrayList<Course> courseList) {
         DefaultTableModel model = (DefaultTableModel) tblregister.getModel();
        
         model.setRowCount(0);
         ArrayList<Course> s= new ArrayList<Course>();
         for(Course u:courseList){
             if(spp.getCourseList().contains(u)){
                 
             }
             else{
                 s.add(u);
             }
         }
         for(Course u : s){
             
             Object[] row =new Object[7];
             row[0]=u.getCourseName();
             row[1]=u.getDescription();
//             row[2]=u.getPrerequisites();
//             row[3]=u.getCourseHours();
             row[2]=u.isTermBased()?u.getTerm()+ " "+u.getTermYear():"On Demand";
             row[3]="Start Date:"+u.getStartDate()+" End Date:"+u.getEndDate();
             row[4]=u.getSessionType();
             row[5]= u.getRatingSystem().getOverallAverageRating();
             row[6]= "Add";
//             row[7]=u.
             model.addRow(row);
    }
}

    private void modifycomponents() {
// jComboBox1.removeAllItems();
//    jComboBox1.addItem("None");
//    jComboBox2.removeAllItems();
//    jComboBox2.addItem("None");
    txtsearch.setVisible(false);
    btnsearch.setVisible(false);
    tblregister.setVisible(false);
    jScrollPane1.setVisible(false);
//    btnderole.setVisible(false);    
    }

    private void populateComboBox(JComboBox<String> jComboBox, ArrayList<String> values) {
        jComboBox.removeAllItems();  // Clear existing items 
        jComboBox.addItem("Select to Filter");
        for (String value : values) {
            jComboBox.addItem(value);
        }    

    }
}
